### PR TITLE
Modify each configuration of Privacy-43

### PR DESCRIPTION
**Pull request by yashirot**
This PR is to modify each configuration of Privacy-43 as it found:
* there is no difference between 1, by default, and 3
* it needs for Private-33 to be 5 to opt out completely.

### CODE REVIEW

**Comment by piroor** [comment]
Sorry I missed this and created #46 ...

**Comment by yashirot** [comment]
> Sorry I missed this and created #46 ...

Do you mean you didn't notice this PR and made another PR, #46, to change almost the same?
Then, to close it and review this PR would be a good way.
What do you think about it?

**Comment by piroor** [comment]
My version #46 now covers changes in this PR and some descriptions are added for more convenience, so I hope to merge it instead of this. Is that OK?

**Comment by yashirot** [comment]
> My version #46 now covers changes in this PR and some descriptions are added for more convenience, so I hope to merge it instead of this. Is that OK?

Yes.
However,  I'd like to make a couple of small fixes to the text of  PR #46 to align with that in GUI.

Then, that I will close PR #45 and then review PR #46 would be better.
What does it sound?

**Comment by yashirot** [comment]
Closed to be consolidated to PR #46.

**Pull request closed without merging**
